using System.Collections.Generic;
using Blizzard.Obstacles;

namespace Blizzard.Constants
{
    public static class ObstacleConstants
    {
        /// <summary>
        /// Alpha color value of obstacle previews (generated by obstacle.CreatePreview())
        /// </summary>
        public const float PreviewAlpha = 0.5f;

        // -- Obstacle Layers --
        public const int ObstacleLayerCount = 2;

        /// <summary>
        /// Sprite sorting layers assigned to obstacle of different obstacle layers
        /// </summary>
        public static readonly Dictionary<ObstacleLayer, int> ObstacleLayerSortingLayers = new()
        {
            { ObstacleLayer.Main, -20 },
            { ObstacleLayer.Floor, -40 }
        };

        /// <summary>
        /// Default obstacle layer, also the one used for temperature calculations
        /// </summary>
        public const ObstacleLayer MainObstacleLayer = ObstacleLayer.Main;

        // -- Obstacle QuadTrees --
        /// <summary>
        /// Maximum allowed portion of queried invalid positions when querying K nearest
        /// in an ObstacleQuadTree
        /// </summary>
        public const float QTMaxAllowedInvalidInQuery = 0.25f;

        /// <summary>
        /// Default maximum depth of ObstacleQuadTree
        /// </summary>
        public const int QTMaxDepth = 12;

        /// <summary>
        /// Default maximum objects per node of ObstacleQuadTree
        /// </summary>
        public const int QTObjectsPerNode = 16;

        /// <summary>
        /// Additional portion of space to add to bounds on QT Rebuild.
        /// </summary>
        public const float QTBoundsPadding = 0.25f;
    }
}