using System.Collections.Generic;
using UnityEngine;

namespace Blizzard.Obstacles
{
    public static class ObstacleConstants
    {
        /// <summary>
        /// Alpha color value of obstacle previews (generated by obstacle.CreatePreview())
        /// </summary>
        public const float PreviewAlpha = 0.5f;

        // -- Obstacle Layers --
        public const int ObstacleLayerCount = 2;
        /// <summary>
        /// Sprite sorting layers assigned to obstacle of different obstacle layers
        /// </summary>
        public static readonly Dictionary<ObstacleLayer, int> ObstacleLayerSortingLayers = new()
        {
            { ObstacleLayer.Main, 20 },
            { ObstacleLayer.Floor, 0 }
        };
        /// <summary>
        /// Default obstacle layer, also the one used for temperature calculations
        /// </summary>
        public const ObstacleLayer MainObstacleLayer = ObstacleLayer.Main;
    }
}