using UnityEngine;

namespace Blizzard.Obstacles
{
    public static class ObstacleConstants
    {
        /// <summary>
        /// Alpha color value of obstacle previews (generated by obstacle.CreatePreview())
        /// </summary>
        public const float PreviewAlpha = 0.5f;
    }
}